name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        php: [8.1]
        composer-flags: [ '' ]
        stability: ['prefer-lowest', 'prefer-stable']
        experimental: [false]
        eventsauce: ['^1.0', '^2.0', '^3.0']
        include:
          - php: 8.1
            stability: 'prefer-stable'
            composer-flags: '--ignore-platform-reqs'
            experimental: false

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - Eventsauce ${{ matrix.eventsauce }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: xdebug

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.stability }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.stability }}-
            ${{ runner.os }}-composer-

      - name: Install specific eventsauce version
        run: |
          composer require "eventsauce/eventsauce=${{ matrix.eventsauce }}" -w --prefer-dist --no-interaction --no-update

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} ${{ matrix.composer-flags }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --verbose

      - name: Run PHP CS Fixer
        if: ${{ matrix.experimental == false }}
        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no || true

      - name: Run PHPStan
        if: ${{ matrix.experimental == false }}
        run: vendor/bin/phpstan analyze -c phpstan.neon
